version: '3.8'

services:
    app:
        build:
            context: .
            dockerfile: docker/Dockerfile
        container_name: todolist-app
        ports:
            - "8081:80"
        volumes:
            - .:/var/www/html
        depends_on:
            - db
        environment:
            - APACHE_DOCUMENT_ROOT=/var/www/html/public

    db:
        image: mysql:8.0
        container_name: todolist-db
        environment:
            MYSQL_ROOT_PASSWORD: "${DB_ROOT_PASSWORD}"
            MYSQL_DATABASE: "${DB_DATABASE}"
            MYSQL_USER: "${DB_USERNAME}"
            MYSQL_PASSWORD: "${DB_PASSWORD}"
        volumes:
            - db_data:/var/lib/mysql
        ports:
            - "3308:3306"

volumes:
    db_data:
